name: Build and Deploy Vite site

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to server via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "dist/**"
          target: "/var/www/matthewbowman.uk/public_live/"
          strip_components: 1

      # Notify Discord on success
      - name: Notify Discord
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d '{"content": "**Build succeeded!** 🎉\nRepository: '"${{ github.repository }}"'\nBranch: '"${{ github.ref_name }}"'\nRun: <'"${{ github.run_url }}"'>"}' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
